---
# Based on https://github.com/marcusrbrown/containers/blob/main/.github/actions/setup/action.yaml
name: Setup
description: Setup build environment using mise

inputs:
  cache-version:
    default: '0'
    description: Cache version. Can be incremented to invalidate the cache.
    required: false

runs:
  steps:
    - name: Install mise
      env:
        MISE_VERSION: 2026.3.17 # renovate: datasource=github-releases packageName=jdx/mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        version: ${{ env.MISE_VERSION }}

  using: composite
