---
# Based on https://github.com/marcusrbrown/containers/blob/main/.github/actions/setup/action.yaml
name: Setup
description: Setup build environment using mise

inputs:
  cache-version:
    default: '0'
    description: Cache version. Can be incremented to invalidate the cache.
    required: false

runs:
  steps:
    - name: Install mise
      env:
        MISE_VERSION: 2026.3.13 # renovate: datasource=github-releases packageName=jdx/mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      with:
        version: ${{ env.MISE_VERSION }}

  using: composite
