bracketSpacing: false
jsxSingleQuote: true
singleQuote: true
tabWidth: 2
plugins:
  - 'prettier-plugin-svelte'
overrides:
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
  - files: '*.svelte'
    options:
      parser: svelte
