bracketSpacing: false
jsxSingleQuote: true
singleQuote: true
tabWidth: 2
overrides:
  - files:
      - '*.json'
    options:
      singleQuote: false
      trailingComma: none
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
