packages:
  - course/pdf-dist/client
  - tutorials

allowBuilds:
  '@sveltejs/kit': true

autoInstallPeers: true
dedupePeerDependents: true
resolutionMode: lowest-direct
resolvePeersFromWorkspaceRoot: true
saveExact: true
saveWorkspaceProtocol: rolling
