bracketSpacing: false
jsxSingleQuote: true
singleQuote: true
plugins:
  - 'prettier-plugin-svelte'
pluginSearchDirs:
  - '.'
overrides:
  - files:
      - '*.json'
    options:
      singleQuote: false
      trailingComma: none
  - files: '*.svelte'
    options:
      parser: svelte
